# Generated by Django 3.1.4 on 2020-12-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_poststatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostStatistic',
        ),
    ]
