# Generated by Django 3.1.3 on 2020-11-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201113_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsetting',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_setting', related_query_name='post_setting', to='blog.post', verbose_name='post'),
        ),
    ]
