# Generated by Django 3.1.4 on 2020-12-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_urlhit_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlhit',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='post'),
        ),
    ]
