# Generated by Django 3.1.4 on 2020-12-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201225_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlhit',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='post'),
        ),
    ]
