# Generated by Django 3.1.4 on 2020-12-28 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201225_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitcount',
            old_name='date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='hitcount',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlhit',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_hit', related_query_name='url_hit', to='blog.post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='urlhit',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
