# Generated by Django 3.1.4 on 2020-12-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201228_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='url_hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.urlhit'),
        ),
    ]
