# Generated by Django 3.1.3 on 2020-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201203_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=200, null=True, verbose_name='Summary'),
        ),
    ]
