# Generated by Django 3.1.4 on 2020-12-30 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201228_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], max_length=10, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 30, 11, 6, 28, 357359, tzinfo=utc), verbose_name='Publish at'),
        ),
    ]
