# Generated by Django 3.1.4 on 2021-01-01 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201230_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.CharField(blank=True, choices=[('Tech', 'تکنولوژی'), ('Car', 'خودرو'), ('Science', 'علمی')], max_length=10, verbose_name='Main category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 1, 1, 8, 50, 24, 106957, tzinfo=utc), verbose_name='Publish at'),
        ),
    ]
