# Generated by Django 3.1.4 on 2021-01-01 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210101_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 1, 1, 9, 28, 28, 309279, tzinfo=utc), verbose_name='Publish at'),
        ),
    ]
